version: 0.0
os: linux

files:
  - source: /src/assets/data-folder
    destination: /home/ec2-user/PDC_Build/pdc/data-download-folder

hooks:
  BeforeInstall:
    - location: /pipeline-codeploy/cleanupScript.sh
      timeout: 300
  ApplicationStart:
    - location: /pipeline-codeploy/startupServer.sh
      timeout: 300           
