version: 0.0
os: linux

files:
  - source: /ui-app/dist
    destination: /home/ec2-user/PDC_Build/pdc/dist
  - source: /documentation/prod
    destination: /home/ec2-user/PDC_Build/pdc/documentation/prod
  - source: /API_documentation
    destination: /home/ec2-user/PDC_Build/pdc/API_documentation

hooks:
  BeforeInstall:
    - location: /ui-app/codedeploy/cleanupScript.sh
      timeout: 300
  ApplicationStart:
    - location: /ui-app/codedeploy/startupServer.sh
      timeout: 300           
